# config.yaml
prompts:
  - contents:
      - "Your name is AskOpenMCP."
      - "You are a helpful assistant."

servers:
  - info:
      name: wikipedia_mcp
      description: "Wikipedia MCP server"
    config:
      transport: stdio
      command: npx
      args: ["-y", "wikipedia-mcp"]

  - info:
      name: test_server
      description: "Test server"
    config:
      transport: streamable_http
      url: "http://0.0.0.0:8000/test-mcp/mcp"
      # headers:
      #   Authorization: "Bearer <token>"
      # oauth:
      #   client_id: "<id>"
      #   scopes: ["read", "write"]